### ISSUE TITLE
none of the new methods are being implemented (probably me being dumb)

### ISSUE THREAD

**Issue by conorpo** [rust-ndarray/ndarray-linalg#387]
```rs
use ndarray_linalg::Inverse;
use ndarray::*;

const DIM : usize = 2;
type Matrix = Array2<f64>;
type Vector = Array1<f64>;
type Edge = (u16, u16);
```

```toml
[dependencies]
ndarray =  { version = "0.16.1", features = ["blas"]}
ndarray-linalg = { version = "0.16.0", features = ["openblas-system"] }
```

Pretty sure I installed openblas correctly using vcpkg, before rust-analyzer wasnt working at all but now its working, just giving me errors whenever I try to call .inv() or .trace() (or any of the new methods)

no method named `inv` found for struct `ArrayBase` in the current scope
method not found in `ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>>`

please let me know what other info yall need.
